#include "ChamberWallControl.h"
#include "BinaryData.h"  // Generated by CMake from juce_add_binary_data

ChamberWallControl::ChamberWallControl(juce::AudioProcessorValueTreeState& state)
    : MonumentControl(state, "time", "TIME")
{
    // Load sprite sheet from embedded BinaryData
    // CMake will convert chamber_wall_time_states.png → chamber_wall_time_states_png
    setSpriteSheet(
        BinaryData::chamber_wall_time_states_png,
        BinaryData::chamber_wall_time_states_pngSize,
        4  // 4 frames (3072px wide / 4 = 768px per frame)
    );
}
